language: node_js
env:
  - NODE_PATH=$(which node)
install:
  - yarn install
  - cd human-connection-api
  - yarn install
  - cd ..
services:
  - mongodb
node_js:
  - "9"
script:
  - yarn lint
  - yarn test
